### ISSUE TITLE
Form action method not forming

### ISSUE THREAD

**Issue by dev-vkagrawal** [soundaranbu/Razor.Templating.Core#35]
When we use regular `<form>` attribute with asp-controller and asp-action html tag helpers then final output does not contain action property of form, instead it contains blank action value on specified `<form>` like `<form action="" method="post">... </form>`
Any solution please?

**Comment by soundaranbu** [comment]
Hi @dev-vkagrawal, is this console app or mvc?

**Comment by dev-vkagrawal** [comment]
Hi @soundaranbu it is from mvc application. From controllers' action method I want to return view's string content along with some other couple of data. 
Everything seems returning properly except the form action value when used with asp-controller and asp-action.

**Comment by soundaranbu** [comment]
Ok I'll look into it this weekend. Between what version of dotnet and the library are you using?

**Comment by dev-vkagrawal** [comment]
I am using .Net Core 3.1

**Comment by dev-vkagrawal** [comment]
Thanks @soundaranbu can you please tell me which version of nuget package with a fix would be compatible with .Net core 3.1 ?

**Comment by soundaranbu** [comment]
Hi @dev-vkagrawal , Currently the fix is in testing phase. I'll release a preview version in one or two days. I'll let you know by then. Thanks

**Comment by soundaranbu** [comment]
Hi @dev-vkagrawal, I've made a pre-release `v1.6.1-rc.1`. please it try out and let me know https://www.nuget.org/packages/Razor.Templating.Core/1.6.1-rc.1

Thanks.

**Comment by dev-vkagrawal** [comment]
Hi @soundaranbu it does not seem working with either version. Still action property of <form> is blank.

**Comment by soundaranbu** [comment]
Ok that's weird. if possible, please send a sample project to reproduce the issue. otherwise, it'll be hard to look into this further. thanks!

**Comment by dev-vkagrawal** [comment]
It is simple mvc project and I have regular view with form element and action property on it. When trying to get html of such view then just action property is blank in resultant view string.

**Comment by soundaranbu** [comment]
Ok then you might need to take a look at this sample mvc project which renders the form action method properly and let me know how it works for you. 

Checkout branch: `release/1.6.x`
https://github.com/soundaranbu/RazorTemplating/tree/release/1.6.x/examples/Mvc/ExampleWebApp.NetCore3_1

Look for this action method: https://github.com/soundaranbu/RazorTemplating/blob/1ff2c21c0ee4b9bd218f4b6f0cca93898dee6264/examples/Mvc/ExampleWebApp.NetCore3_1/Controllers/HomeController.cs#L66-L70

**Output Url:** `/Home/TagHelpers`

**Template:**
![image](https://user-images.githubusercontent.com/29944019/151729010-930475c1-da31-4c43-9fed-531ddd7b7902.png)

**Output:**
![image](https://user-images.githubusercontent.com/29944019/151728423-f40c4b74-8f31-4e19-87b2-c8d39c291a97.png)

**Comment by dev-vkagrawal** [comment]
Hi, I cloned project but solution explorer shows just .Net 6 project, while I am trying to see .Net Core 3.1 project to test. Can you please tell me what else I need to change to make it work with .net core 3.1?
Please see attached image.
![image](https://user-images.githubusercontent.com/58482443/153046390-90c9ff4d-66f3-4846-9217-9340a08457ba.png)

**Comment by soundaranbu** [comment]
Hi @dev-vkagrawal, please checkout branch  `release/1.6.x` where you can find the project

**Comment by soundaranbu** [comment]
Closing this one as I have shown the output with screenshots https://github.com/soundaranbu/Razor.Templating.Core/issues/35#issuecomment-1025310067

In case, if you still have issues, feel free to reopen. Thanks :)
