### ISSUE TITLE
Issue with UrlHelper

### ISSUE THREAD

**Issue by cadilhac** [soundaranbu/Razor.Templating.Core#40]
Hi,

I try to generate a link inside a template, using:

```cs
@Url.RouteUrl(<routename>)
```

RouteUrl returns null.

Thanks

**Comment by soundaranbu** [comment]
Hi, Please assist with more info:

.NET Version: 
Project Type: 
Razor.Templating.Core Version: 
Expected Output:
Sample repo to reproduce(if possible):

**Comment by soundaranbu** [comment]
Hi @cadilhac, I had a look. `@Url.RouteUrl` will work only in MVC app as it requires the [routing features](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-6.0#generate-urls-by-route) which is not supported by the library. 
A quick workaround is to call `@Url.RouteUrl` from the controller action method & then pass it to the ViewModel. 
Hope it helps. Thanks.

**Comment by cadilhac** [comment]
Yes. Sorry, I had not been able to create a repro yet. And yes, I'm using MVC and was already creating the link in the controller as a workaround. Sad that you can't solve it. Cheers.

**Comment by soundaranbu** [comment]
I've updated the documentation that UrlHelper is not supported. Hence closing. Please feel to reopen if there are any suggestions.
Thanks :)
