### ISSUE TITLE
External css files do not work

### ISSUE THREAD

**Issue by HoehensteigerGames** [soundaranbu/Razor.Templating.Core#41]
I tried everything i knew but it was not possible to use an external CSS file.
Everything works fine like in the document and in the example.

that is a screenshot of my current Project:
![image](https://user-images.githubusercontent.com/58444802/167204396-06d44124-0a30-40a3-a136-9cc458c8dfef.png)

What have i don wrong? is it possible to use External css files?

**Comment by soundaranbu** [comment]
Hi @HoehensteigerGames, I'll look into this & let you know. In the mean time, let me know what's your expected output? & what's your final goal after rendering the template? 
If you're doing this for email templating, I would suggest you to keep the styles in the same file.

**Comment by HoehensteigerGames** [comment]
yes thats the goad. I Want to get an Email template and yes at the moment i will use them in the same file. But the mail will be very big. So it would be conventient to split up the file.

**Comment by bentoaldohax** [comment]
Is there any update on this? I am having the same problem.

**Comment by soundaranbu** [comment]
Yes there's an update. I updated the README but missed to update here. `@Url.Content` is not supported by the library. 
If the aim is to keep the styles separate, please try partial view instead. Otherwise we need to keep it in the same file only.
Hope it helps.

**Comment by soundaranbu** [comment]
I've updated the documentation that this is not supported. Feel free to reopen if there are any suggestions.
Thanks :)
