### ISSUE TITLE
AWS lambda support?

### ISSUE THREAD

**Issue by vladopandzic** [soundaranbu/Razor.Templating.Core#44]
I tried using this library on AWS lambda but I get error than views are unable to find.
My views are localted in separate RLC which I referenced from lambda project

**Comment by soundaranbu** [comment]
Hi @vladop , I haven't tested on AWS lambda yet. I'll test & let you know.

**Comment by kyle-covertree** [comment]
We are using this library in AWS Lambdas without any modifications. All you should need to include in the Lambda project `csproj` file is this:

```csproj
    <PropertyGroup>
        <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Razor.Templating.Core" Version="1.9.0" />
    </ItemGroup>
```

**Comment by soundaranbu** [comment]
Thats great to know @kyle-covertree. I'm closing this issue then :)
