### ISSUE TITLE
Add option to render views without layout

### ISSUE THREAD

**Issue by soundaranbu** [soundaranbu/Razor.Templating.Core#53]
This is to refer to an issue for PR #52 by @mobiletonster

**Comment by soundaranbu** [comment]
Hi @mobiletonster, your contributions are now merged into the main branch, and a pre-release package has been released. 
 https://github.com/soundaranbu/Razor.Templating.Core/releases/tag/v1.9.0-rc.1

Let me know how it works for you.

Appreciate your time and efforts to bring useful features to the library!  🙌

**Comment by josh-berg** [comment]
@soundaranbu Any idea when the full version 1.9.0 will be released? Testing out `RenderPartialAsync` in the pre-release and it's working great! 😄

**Comment by josh-berg** [comment]
No worries! Appreciate the update. Thanks!

**Comment by soundaranbu** [comment]
`v1.9.0` has been released. @mobiletonster Thank you for your contribution again!
