### ISSUE TITLE
AddRazorTemplating doesn't return IServiceCollection

### ISSUE THREAD

**Issue by gbtb** [soundaranbu/Razor.Templating.Core#57]
Hello.

It would be more convenient if AddRazorTemplating extension method followed builder pattern and returned IServiceCollection, so that method call chain didn't break.

**Comment by soundaranbu** [comment]
Hi @gbtb, thanks for the feedback. Would you like to share what problems you are facing now with the current pattern? And how can it be avoided with the proposed builder pattern? 
Some code snippets will be helpful too.

**Comment by gbtb** [comment]
I meant that it would be nice if AddRazorTemplating could follow usual pattern for registering dependencies in Service collection like that:
```
services
      .AddLogging()
     .AddHttpContextAccessor()
     .AddRazorTemplating()
     .AddSingleton<Foo>()
     .AddTransient<Bar>()
```
It would imply following signature for the method - `public static IServiceCollection AddRazorTemplating(this IServiceCollection services)`. However, after reading README.md carefully I finally saw your comment about AddRazorTemplating being required to register the last (I skimmed over it at first, sorry 🙈 ) That is somewhat unusual requirement for deps registration, but if that's necessary I guess having `void AddRazorTemplating` is reasonable, and you can close this issue.

**Comment by soundaranbu** [comment]
It was required to build the service provider for the `RazorTemplatingEngine` static class. I don't know if there's any better way to do it. Feel free to reopen if you have any suggestions. 
Thanks :)
