### ISSUE TITLE
Error on render/embed .razor component inside .cshtml

### ISSUE THREAD

**Issue by tharlab** [soundaranbu/Razor.Templating.Core#61]
hi i wanna embed/render my .razor component/blazor into .cshtml but it generating error....

`Html.RenderComponentAsync<BlazorApp.Pages.SinglePbn>(RenderMode.WebAssemblyPrerendered)`

or maybe better you can add the package support to render blazor/.razor component directly instead .cshtml.... I dont really like much cshtml

so we can use blazor/.razor component directly in the route....
thanks

**Comment by soundaranbu** [comment]
Hey @tharlab, thanks for raising the issue. Rendering `.razor` components within `.cshtml` files are not tested/supported yet in this library.

However, there's an official feature landing in .NET 8 to render `.razor` files outside of the HTTP context. You may be interested in this https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-components-outside-of-aspnetcore?view=aspnetcore-8.0

Let me know if that sounds good to you!

**Comment by soundaranbu** [comment]
I hope that I clarified the query. Feel free to reopen if anything. Cheers
