### ISSUE TITLE
.net 5 error when including  services.AddRazorTemplating();

### ISSUE THREAD

**Issue by Cpousson** [soundaranbu/Razor.Templating.Core#65]
version 1.6
I am receiving an error message when I include the middleware in the configureservices() method:

TypeLoadException: Could not load type 'System.Web.PreApplicationStartMethodAttribute' from assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

Is there a step I am missing?

**Comment by soundaranbu** [comment]
Hi @Cpousson, I'm sorry that you are facing this issue. But, have you tried running one of the sample applications in this repository? https://github.com/soundaranbu/Razor.Templating.Core/tree/master/examples/Mvc/ExampleWebApp.Net5_0

From your error message, I could see that the type `System.Web.PreApplicationStartMethodAttribute` is supported only on .NET Framework https://learn.microsoft.com/en-us/dotnet/api/system.web.preapplicationstartmethodattribute?view=netframework-4.8.1

and one of the stackoverflow answer suggests the same https://stackoverflow.com/a/47891992/11033552

So I don't think this issue has anything to do with this library. But please try these solutions and let me know. 

Cheers,

**Comment by soundaranbu** [comment]
I hope I've answered your issue. I'm closing this now. Please feel free to reopen if required. Thanks :)
