### ISSUE TITLE
Getting the issue while rendering the view

### ISSUE THREAD

**Issue by rnarasimhamurthyjjk** [soundaranbu/Razor.Templating.Core#73]
![image](https://github.com/soundaranbu/Razor.Templating.Core/assets/156445060/7799e17b-5b87-4c05-9df5-8ccf2a7c2cd2)

**Comment by asos-soundaranbalagan** [comment]
Hey @rnarasimhamurthyjjk, this doesn't seem right which is the views path and where the views are held. You may want to use the Razor Class Library.

Please follow step by step instructions here https://soundaranbu.medium.com/render-razor-view-cshtml-to-string-in-net-core-7d125f32c79 or checkout one of the console app example in this repo.

I hope that helps.

**Comment by soundaranbu** [comment]
Hey @rnarasimhamurthyjjk, this doesn't seem right which is the views path and where the views are held. You may want to use the Razor Class Library.

Please follow step by step instructions here https://soundaranbu.medium.com/render-razor-view-cshtml-to-string-in-net-core-7d125f32c79 or checkout one of the console app example in this repo.

I hope that helps.

**Comment by rnarasimhamurthyjjk** [comment]
The above link doesnt seem to open

**Comment by soundaranbu** [comment]
Ok great, I fixed the link anyway. Closing this issue as you got the solution.

Thanks:)
